title: Maxx Turing
description: > # this means to ignore newlines until "baseurl:"
  Blog posts by Maxx Turing
permalink: ':title'
# permalink: ':title'
baseurl: '/blog' # the subpath of your site, e.g. /blog
url: 'http://maxxturing.com/' # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: maxxturing #if your site has a twitter account, enter it here

# Author Settings
author: Maxx Turing # add your name
author-img: maxx-turing.png # add your photo
about-author: Sharing things I'm learning through my work with startups and other interests # add description
social-twitter: maxxturing # add your Twitter handle
social-instagram: maxxturing # add your Instagram handle
social-github: maxxturing # add your Github handle
social-linkedin: maxxturing # add your Linkedin handle
social-email: maxx@maxxturing.com # add your Email address

# Disqus
discus-identifier: maxxturing # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: '/page/:num'

exclude: ['node_modules', 'gulpfile.js', 'package.json', 'yarn.lock']
